### ISSUE TITLE
Superscript and subscript offsets in the OS/2 table are bad

### ISSUE THREAD

**Issue by matthiasclasen** [silnrsi/font-gentium#15]
These values seem nonsensical - the super- and subscript offset values are the same, which does not make sense.
And the sizes seem smaller than they should be.

This screenshot compares super- and subscripts done using the OS/2 metrics with just using the Unicode codepoints:

![gentium](https://user-images.githubusercontent.com/4834845/193455949-61a78acb-391f-4030-a785-1bf26372d618.png)

**Comment by jvgaultney** [comment]
Yeah - those are incorrect in our fonts. I'll look at fixing them in a future release. The reality is that those metrics are rarely ever used by developers. In the 20 year history of Gentium I think this is the first time anyone has ever reported a problem with them.

**Comment by matthiasclasen** [comment]
I've used them in pango for implementing nested super- and subscripts, and got this report: https://gitlab.gnome.org/GNOME/pango/-/issues/702

**Comment by jvgaultney** [comment]
We are planning to add common OT 'sups' and 'subs' features in the next release, but I agree that it will not address nested ones. The OS/2 metrics will be fixed in v6.2 so you'll be able to nest things.

However I still think that Pango should not use those metrics *except* in the case of nesting. The proper way to implement this in Pango long-term would be to use the OpenType 'subs' and 'sups' features if they exist, and use the OS/2 metrics as a fallback.

**Comment by matthiasclasen** [comment]
I might look into it at some point

**Comment by khaledhosny** [comment]
IMO, `sups` and `subs` features in OpenType are mis-desisgned, the pre-scaling and pre-positioning glyphs makes it insuffcient for implmenting general `<sub>` and `<sup>` markup:

1. The font needs to provide superscaipt and subscript versions of all its glyphs, otherwise any glyph not covered by these features will fallback to full size glyph at baseline, which is worse than losing optical adjustment.
2. They support only one level of subscripts and superscripts, so multiple levels/nesting of the tags can’t be supported.

OpenType math’s [`ssty`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-ssty) feature neatly fixes both issues by keeping the *script glyphs full size but optically adjusted for use at smaller font size and the `MATH` table has parameters to how much to scale and position them. Unfortunately it isn’t supported outsize the few OpenType math fonts.

Anyway, my suggestion is to fix the OS/2 parameters in the fonts any way to give results as close as possible to pre-designed glyphs, so apps can use them at least for fallback.

**Comment by jvgaultney** [comment]
I agree about the OT `sups` and `subs` features. We're adding those only for numerals - not letters or other symbols. My suggestion that Pango use the OT features for non-nested was also only for numerals.

**Comment by jvgaultney** [comment]
OS/2 metrics have been changed in v6.200 to be more consistent.
