### ISSUE TITLE
smallcaps lowercase a is taller than other miniscule smallcaps

### ISSUE THREAD

**Issue by dankamongmen** [silnrsi/font-gentium#28]
Hey again! I've been making fairly wide use of smallcaps in my novel (written with Gentium Book Plus), and I notice that the lowercase smallcaps 'a' is taller than the other smallcaps. Here are some examples:

![2023-09-03-113239_678x79_scrot](https://github.com/silnrsi/font-gentium/assets/143473/1dfcd49d-b2fd-4d7f-a45c-05bdc69c7b2f)

These correspond to:

`\textsc{Abacus} or \textsc{Angola}.`

![2023-09-03-113507_685x196_scrot](https://github.com/silnrsi/font-gentium/assets/143473/2006df90-4281-4f3f-b9d0-2df3798594f8)

it's less obvious here (maybe there's some more divergence among the smallcaps?), but take a look at "arduous" and "an". yeah, i think maybe 't' is taller than most other smallcaps, making 'a' look not so tall when they're next to one another.

maybe this is intended behavior? it looks odd to me, though.

sorry to complain about such a small detail!

**Comment by jvgaultney** [comment]
I don't mind even small bug reports. I suspect the problem may be related to hinting - routines that try to optimize display at small sizes and lower-resolution environments.

The small cap A is *slightly* taller than some other small caps, just as the capital A is taller than most capitals. This is to offset a common optical illusion that letters that are pointed or curved at the top look too short if they are the exact same height. However in your screenshot the difference is greatly exaggerated. Here is the normal (unhinted) sizes:

![image](https://github.com/silnrsi/font-gentium/assets/4226750/639dae2e-2455-4836-b0ac-e93f8afede65)

If the problem is hinting then it might only appear on screen at certain sizes. Printing may look fine. To test this print out a page and see if the difference is as extreme as on screen.

Other ideas:

- Be sure you're using the latest release of Gentium Plus. We recently changed how we add hinting to the fonts to improve screen display.
- Try other viewers/editors. If you're looking at PDFs try a different viewer.

**Comment by dankamongmen** [comment]
i really appreciate your friendliness and thoughtful replies. i'll print things out this evening and let you know the results.

**Comment by dankamongmen** [comment]
btw, you're in the ACKs =]:

![2023-09-04-140332_625x261_scrot](https://github.com/silnrsi/font-gentium/assets/143473/171a4fe8-3fac-4329-b5d5-c277c5535653)

**Comment by dankamongmen** [comment]
Excellent news -- following a `dpkg-reconfigure fontconfig-config`, my smallcaps As look great!

The necessary change was from "Autohinter" to "Native".

I have no doubts that, when printed, they look fine. I'll reopen this if that assumption turns out invalid.

Sorry to have wasted your time! Great work!

**Comment by jvgaultney** [comment]
Great! That's a good tip for folks using fontconfig - thanks.
