### ISSUE TITLE
Bold Italic not working on Word for Mac

### ISSUE THREAD

**Issue by mlanglois** [silnrsi/font-gentium#6]
Hi! I am so happy that Gentium Plus is now available in Bold and Bold Italic.
However, I noticed a bug in Word for Mac: the Bold Italic is not correctly displayed but substituted by a "fake" bold italic which Word displays when a font is missing.
This bug seems to only affect Microsoft Office, as I see no problem with e.g. TextEdit or LibreOffice. The font is correctly installed and works fine with other software. Microsoft Office lists the font in the drop-down list, so it knows it's there.
I can't figure out why it's not correctly displayed.
I have Word for Mac 16.53 running on MacOS 11.5.2.
Has anyone encountered the same issue? Is there a solution? Thanks!

**Comment by mlanglois** [comment]
There is a related issue with Gentium Book Plus: the Bold variant is substituted by (or displayed as?) the Bold Italic variant!
So: in both the "Gentium" and "Gentium Book" series, Word seems to have trouble identifying which variant is "Bold" and "Bold Italic". Please note that I tried uninstalling the fonts and adding them again, and that I tried both the 6.000 and 6.001 versions.

**Comment by jvgaultney** [comment]
Yes, we and one other user have seen this problem. Word is not properly linking the font family together. It seems to be a bug introduced in macOS Word 16.52 and still not fixed in 16.53. We saw no problems with Word 16.51 and our version 6+ fonts.

This isn't unique to our fonts. Some of the fonts that ship with macOS have the same problem (Charter, Baskerville, Palatino). Those are just a few examples of wider problem. Some other fonts like Cambria work fine.

Please complain to Microsoft! The more they hear from users the more attention they will give to it. A post on a Microsoft Forum remains unanswered:

https://techcommunity.microsoft.com/t5/office-for-mac/bold-italics-not-working-on-word/m-p/2625182

We have found no way to fix the problem or to make changes to the fonts to work around the bug.

There are two standard things to try when font family relationships turn sour in MS macOS apps:

- Clear your font caches. Here's a good article on that, although since the fonts are working fine in other apps it's highly unlikely that it will help: https://glyphsapp.com/learn/eliminating-font-cache-problems

- Completely uninstall and reinstall all Microsoft Office apps. Yeah that's a bit extreme, but that seems to be Microsoft's standard response.

I hope one of those might help you. I'll keep trying to find a solution. If you discover one please let us know. As a Mac user myself this is very frustrating!

**Comment by jvgaultney** [comment]
This seems to be fixed in Word 16.55 build 21100201. That build number is important, as earlier 16.55 builds were not fixed. Can anyone else confirm that this is now working again?

**Comment by jvgaultney** [comment]
Thanks for confirming that. Word version numbers are odd and seem to differ between countries and product variants. However the build numbers seem to be consistent and follow a calendar date pattern.
